return{}
-- return {
--   'nvim-java/nvim-java',
--   dependencies = {
--     'nvim-java/lua-async-await',
--     'nvim-java/nvim-java-core',
--     'nvim-java/nvim-java-test',
--     'nvim-java/nvim-java-dap',
--     'MunifTanjim/nui.nvim',
--     'neovim/nvim-lspconfig',
--     'mfussenegger/nvim-dap',
--     "nvim-java/nvim-java-refactor",
--     {
--       'williamboman/mason.nvim',
--       opts = {
--         registries = {
--           'github:nvim-java/mason-registry',
--           'github:mason-org/mason-registry',
--         },
--       },
--     }
--   },
--   require('lspconfig').jdtls.setup({
--     java_debug_adapter = {
--       enable = true,
--     },
--   })
-- }
--
